version: '3.9'

services:
  # Mongo service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node application
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      MONGODB_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}