apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db_service }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db_service }}
  template:
    metadata:
      labels:
        app: {{ .Values.db_service }}
    spec:
      containers:
        - name: {{ .Values.db_service }}
          image: {{ .Values.db_image }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---
# App Container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.web_service }}
  template:
    metadata:
      labels:
        app: {{ .Values.web_service }}
    spec:
      containers:
        - name: {{ .Values.web_service }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always