
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
spec:
  selector:
    app: {{ .Values.web.name }}
  ports:
    - port: {{ .Values.web.containerPort }}
      targetPort: {{ .Values.web.containerPort }}
  type: ClusterIP

